# Generated by Django 4.1.7 on 2023-05-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loans',
        ),
    ]
